source/Egharpay/Models/CentreViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Egharpay.Entity;

namespace Egharpay.Models
{
    public class CentreViewModel : BaseViewModel
    {
        public Centre Centre { get; set; }
    }
}

source/Egharpay/Controllers/CentreController.cs
using Egharpay.Business.Interfaces;
using Egharpay.Entity;
using Egharpay.Entity.Dto;
using Egharpay.Extensions;
using Egharpay.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Egharpay.Controllers
{
    public class CentreController : BaseController
    {
        private readonly IEgharpayBusinessService _EgharpayBusinessService;

        public CentreController(IEgharpayBusinessService EgharpayBusinessService) : base(EgharpayBusinessService)
        {
            _EgharpayBusinessService = EgharpayBusinessService;
        }
        // GET: Centre
       // [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(new BaseViewModel());
        }

        // GET: Centre/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var organisationId = UserOrganisationId;
            var viewModel = new CentreViewModel
            {
                Centre = new Centre
                {
                    OrganisationId = UserOrganisationId
                }
            };
            return View(viewModel);
        }

        // POST: Centre/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CentreViewModel centreViewModel)
        {
            var organisationId = UserOrganisationId;
            if (ModelState.IsValid)
            {
                centreViewModel.Centre.OrganisationId = UserOrganisationId;
                centreViewModel.Centre = EgharpayBusinessService.CreateCentre(UserOrganisationId, centreViewModel.Centre);
                return RedirectToAction("Index");
            }
            return View(centreViewModel);
        }

        // GET: Centre/Edit/{id}
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var centre = EgharpayBusinessService.RetrieveCentre(UserOrganisationId, id.Value);
            if (centre == null)
            {
                return HttpNotFound();
            }
            var viewModel = new CentreViewModel
            {
                Centre = centre

            };
            return View(viewModel);
        }

        // POST: Centre/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CentreViewModel centreViewModel)
        {
            if (ModelState.IsValid)
            {
                centreViewModel.Centre.OrganisationId = UserOrganisationId;
                return RedirectToAction("Index");
            }
            var viewModel = new CentreViewModel
            {
                Centre = centreViewModel.Centre
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult List(Paging paging, List<OrderBy> orderBy)
        {
            return this.JsonNet(EgharpayBusinessService.RetrieveCentres(UserOrganisationId, orderBy, paging));
        }

    }
}

source/Egharpay/Views/Centre/Create.cshtml
@model Egharpay.Models.CentreViewModel

@{
    ViewBag.Title = "Create";
}

<h3>Create</h3>

<div class="x_panel">
    <div class="x_title">
        <h2>Centre <small>create Centre and then manage</small></h2>
        <ul class="nav navbar-right panel_toolbox">
            <li>
                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="#">Settings 1</a>
                    </li>
                    <li>
                        <a href="#">Settings 2</a>
                    </li>
                </ul>
            </li>
            <li>
                <a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        @using (@Html.BeginForm("Create", "Centre"))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal form-label-left">

                <div class="form-control-required-example"> = Required</div>
                <div class="item form-group">
                    @Html.LabelFor(model => model.Centre.Name, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.Centre.Name, new { @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.Centre.Name, "", new { @class = "help-block" })
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-3">
                        <button id="send" type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div>
    <a href="@Url.Action("Index")" class="btn btn-primary" role="button">
        <span class="fa fa-chevron-left"></span>&nbsp;Back to list
    </a>
</div>

source/Egharpay/Views/Centre/Index.cshtml
@using Egharpay.Extensions
@{
    ViewBag.Title = "Centre";
}
<div class="" ng-controller="CentreController as model">
    <div class="row" ng-controller="CentreController as model">
        <div class="col-lg-12">
            <h3>
                Centres
            </h3>
        </div>
    </div>

    <div class="row">
        @if (User.IsInAnyRoles("Admin"))
        {
            <div class="col-lg-12">
                <a class="btn btn-primary btn-lg" href="@Url.Action("Create", "Centre")">
                    <i class="fa fa-user"></i> Create
                </a>
            </div>
        }
    </div>
    <br />
    <div class="ibox-content">
        <div class="row m-b-sm m-t-sm">
            <div class="col-md-12">
                <div class="input-group">
                    <input type="text" placeholder="Search" class="input-sm form-control"> <span class="input-group-btn">
                        <button type="button" class="btn btn-sm btn-primary"> Go!</button>
                    </span>
                </div>
            </div>
            <div class="project-list">
            </div>
        </div>
        <div class="row m-b-sm m-t-sm">
            <div class="col-md-3 form-inline">
                @Html.Partial("Pagination/_pageSize")
            </div>
            <div class="col-md-9 text-right">
                @Html.Partial("Pagination/_pageInformation")
            </div>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-md-3" ng-repeat="centre in model.centres">
                <div class="ibox">
                    <div class="ibox-content product-box">
                        <div class="product-imitation">
                            [Info]
                        </div>
                        <div class="product-desc">
                            <span class="product-price">
                                Active
                            </span>
                            @* <small class="text-muted"><span class="label label-info pull-left">Active</span></small>*@
                            <br />
                            <a href="#" class="product-name"><strong ng-bind="centre.Name"></strong></a>
                            <div class="small m-t-xs">
                                Many desktop publishing packages and web page editors now.
                            </div>
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="m-t text-left">
                                        <a href="#" class="btn btn-xs btn-outline btn-primary">Info <i class="fa fa-long-arrow-right"></i> </a>

                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="m-t text-right">
                                        <a href="#" class="btn btn-xs btn-outline btn-warning">Info <i class="fa fa-long-arrow-right"></i> </a>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-inline">
            <div class="row">
                <div class="col-lg-12">
                    @Html.Partial("Pagination/_pagination")
                </div>
            </div>
        </div>
    </div>
</div>